### ISSUE TITLE
Adding sleep() and usleep() to the clock

### ISSUE THREAD

**Issue by ste-wilkinson** [Lendable/clock#9]
I've seen an example clock implementation that also includes the sleep functions, which seems sensible to me given it deals with time and will allow mocking sleep without writing a wrapper util or importing a function stubbing library. I recently needed this functionality, so in the interim I created a wrapper but it would be good to see what the appetite is for adding it to this library.

**Comment by ben-challis** [comment]
I personally feel this sits elsewhere, as it regards time but not a Clock, I feel in a test environment when you've got a `Clock` where the time doesn't move, to ask the clock to sleep for a duration, and the time _not_ shift would be rather weird behaviour.

I'm all for us packaging this up as a dedicated small library, we've got it now in roughly identical formats in multiple internal projects.

I.e. they all roughly follow:

```php
interface Sleep
{
    public function sleep(int $microseconds): void;
}

final class NativeSleep implements Sleep
{
    public function sleep(int $microseconds): void 
    {
        \usleep($microseconds);
    }
}

final class InterrogatableMockSleep implements Sleep 
{
    public function sleep(int $microseconds): void 
    {
        // records the sleep call internally.
    }

    public function sleepCount(): int {}
    public function otherInterrogationMethodsEtc() {}
}
```

**Comment by ste-wilkinson** [comment]
Fair enough, I think we can close this issue then :+1:
